### ISSUE TITLE
Help with setup/install guide

### ISSUE THREAD

**Issue by etxahun** [ivan-novakov/php-saml-ecp-client#1]
Hi Ivan, 
I'm currently working in a shibboleth SP/IdP environment and would like to add an ecp-client to it. Your implementation looks very interesting and would like to know if you could share how it could be setup or the way that you test it.

Thanks in advance for your help,

Etxahun.

**Comment by ivan-novakov** [comment]
Hi,
the status of this library is "experimental". It means, that it's not 100% complete and I haven't tested it in different environments.
Anyway, I agree, that I should provide some information about how to setup and use the library. I'll try to write something in the next few days, when I find some time.

**Comment by etxahun** [comment]
Hi Ivan !!
thank your for your quick response. I will wait for your explanation ;).

**Comment by ivan-novakov** [comment]
I just committed a README and updated the inline docs. It's not perfect but at least it's something :).
Current API docs can be found here:

http://debug.cz/apidocs/ecp/

**Comment by etxahun** [comment]
Thank you Ivan !!! 

I'll take a look to the documentation.
